### ISSUE TITLE
Ensure XML tests are anonymised for publication

### ISSUE THREAD

**Issue by alexstuart** [ukf/ukf-testbed#10]
This repository is hosted on public github.com so we must ensure that data (fragment files) which are in the tests does not contain PII nor data that's been given to the UK federation on the understanding that it's not to be published.

The current tests need some light editing, although this issue is mostly to update the documentation to remind people writing tests.

**Comment by philsmart** [comment]
I will anonymise any PII in the existing tests.

**Comment by philsmart** [comment]
The PII has been removed from the current test suite. I've started a [page](https://github.com/ukf/ukf-testbed/wiki/Example-Test-Entity) to explain an example XML Entity Descriptor for testing. I will hold this open until that is complete.

**Comment by philsmart** [comment]
I added that Wiki page. It seems OK for now. I am sure it might be amended as we ad more tests.
