### ISSUE TITLE
Refactor after adoption of MDA 0.10

### ISSUE THREAD

**Issue by iay** [ukf/ukf-testbed#100]
Now that the UK federation deployment has both moved to MDA 0.10.0 and removed Xalan from its tooling, three of the four current members of the validator farm are no longer needed.

I don't think we should strip everything down to a single validator at this point, however, as one important future use of the testbed will be to test other such migrations while they are in development.

I therefore propose the following refactoring:

* Entirely remove the two validators that are based on MDA 0.9. These are derived from the `ianayoung/md-validator:0.9` container. We're not going to return to those configurations, and I don't want to have to think about MDA 0.9 with any of my hats on. This also means that I can mentally retire the 0.9 branch of the `iay/md-validator` repository, which hasn't really been kept as well up to date as the main branch, partly because Snyk doesn't know how to monitor branches.
 * Review the existing tests and simplify out anything that was targeted at those validators. For example:

```yaml
override:
 - endpoint : v09
   skip: true
 - endpoint : [v09x, v010x]
   expected:
   - status: error
```

  The override for the `v09` endpoint here can be entirely removed, and the reference to the `v09x` endpoint can be simplified out.

* Refactor the remaining two validators (`v010`, `v010x`) into (spitballing names) `prod` and `next`, which at present would both work off copies of the current production branch. One sub-task at this stage would be to again trawl through the existing tests and fix them up: ideally, there should be no current need for any overrides. Note, however, that it's not necessarily trivial: the current production branch is closest to the `v010x` validator in the current configuration, so in the above example it's the `override` for `v010x` that will become the baseline. How much of this rototilling is needed will depend on some non-obvious decisions made in individual tests.

**Comment by philsmart** [comment]
LGTM. 

I guess implicit in this, we will need to update the `ukf-meta-prod` overlay to be the newest version of the current production branch, then rename the `ukf-meta-239` overlay to something like `ukf-meta-next` (or similar) which is the same as the `ukf-meta-prod` overlay for now, and then finally add them into the `prod` and `next` validators as appropriate.

**Comment by philsmart** [comment]
Which I guess then leads to the other question about how we keep those overlays in synch with the production branch.

**Comment by iay** [comment]
Yes, updating that stuff is implicitly part of the third part of the operation (refactoring the `v010` validators). I'm in two minds as to whether to go down to one copy of the production content or to keep two. At this stage, both of those would be set to the same, production, content as we don't yet have a major shift in progress (I don't yet count the MDA 1.0 update).

In terms of keeping things in sync, I think it's going to be a manual operation for some time. Much longer term I've always seen it as something that could be done "live" from an adjacent or remote copy of the repository: just suck the relevant content out when you need it to run a test. There are definitely upsides to that but the downside is that things can change when you're not expecting them to.

**Comment by philsmart** [comment]
Agreed. Maybe a task for me to add a wiki page on how to keep things in sync. I am not sure I remember and so that could firm that up (and be useful for others).

**Comment by iay** [comment]
There's a `100-refactor` branch for this. First commit performs both of the first two phases: removing the `v09` and `v09x` endpoints, and reworking test configurations so that they no longer reference those endpoints.

The next stage is the actual refactoring; I should get to it tomorrow after which I will fire up the PR and look for review.
